# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FarmEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Farm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.FarmEmployee')),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('employees_involved', models.ManyToManyField(to='panopticon.FarmEmployee')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Farm')),
                ('reporter', models.ManyToManyField(to='panopticon.CrewLead')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sector Name')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.CrewLead')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Sector'),
        ),
        migrations.AddField(
            model_name='crewlead',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.FarmEmployee'),
        ),
        migrations.AddField(
            model_name='crewlead',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Sector'),
        ),
    ]
