# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('BOOLEAN', 'BOOLEAN'), ('CONTINUOUS', 'CONTINUOUS'), ('INTEGER', 'INTEGER'), ('STRING', 'STRING')], max_length=24)),
                ('required_from_lead', models.BooleanField(default=True, verbose_name='Required from lead?')),
                ('required_frequency', models.IntegerField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('BIANNUALLY', 'BIANNUALLY'), ('ANNUALLY', 'ANNUALLY')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=9999)),
                ('index', models.IntegerField()),
                ('customField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.CustomField')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='dateIncapacitated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FarmEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Farm')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_farms', models.ManyToManyField(related_name='list_of_all_farms', to='panopticon.Farm')),
                ('current_farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='panopticon.Farm')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.FarmEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employees_involved', models.ManyToManyField(to='panopticon.FarmEmployee')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Farm')),
                ('reporter', models.ManyToManyField(to='panopticon.CrewLead')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qualification')),
                ('description', models.CharField(max_length=300, verbose_name='Description of qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sector Name')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.CrewLead')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=10000)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.CrewLead')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Sector'),
        ),
        migrations.AddField(
            model_name='dateincapacitated',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.FarmEmployee'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='return_to_work',
            field=models.ManyToManyField(to='panopticon.dateIncapacitated'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Sector'),
        ),
        migrations.AddField(
            model_name='crewlead',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panopticon.FarmEmployee'),
        ),
        migrations.AddField(
            model_name='crewlead',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='panopticon.Qualification'),
        ),
        migrations.AddField(
            model_name='crewlead',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticon.Sector'),
        ),
    ]
